[worker]
name = "api"

[[ingress]]
name = "api-http"
protocol = "http"
port = 3000
public = true
record = "@"

[[kv]]
kv_id = "user-counters"
binding = "USER_COUNTERS"
access = "read-write"

[[bucket]]
bucket_id = "visit-requests"
binding = "VISIT_REQUESTS_BUCKET"
access = "read-write"

[[queue.producer]]
queue_id = "visit-events"
binding = "VISIT_EVENTS_QUEUE"

[observability]
enable = true
prometheus_metrics = "/_/metrics"

[observability.grafana]
sources = "../grafana/sources.json"

[[secret]]
name = "kava.fund/visit-counter/api-token"
binding = "VISIT_COUNTER_API_TOKEN"

[[dashboard]]
name = "API Overview"
path = "../grafana/dashboards/api-overview.json"
